### PR TITLE
Set backends explicitly for read_image and rotate

### PR DESCRIPTION
**Pull request by yuyu2172**
Merge after https://github.com/chainer/chainercv/pull/857

`resize` is similarly modified in #781

### CODE REVIEW

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Pull request merged**
