### PR TITLE
install Cython and numpy manually

### PR DESCRIPTION
**Pull request by knorth55**
@yuyu2172 
Because you use `numpy` and `Cython` in `setup.py`, we need to install them manually before running `pip install chainercv`

You can test it like
```bash
docker pull ubuntu
docker run -it ubuntu /bin/bash
# in docker session
apt-get update
apt-get install python-pip
pip install -U pip
pip install chainercv
# installation fails

pip install Cython
pip install numpy
pip install chainercv
# you can successfully install chainercv
```

Related https://github.com/ros/rosdistro/pull/15441

### CODE REVIEW

**Comment by yuyu2172** [comment]
Thank you for a PR!
Your code snippet is very helpful for us to improve our installation code.
We are working on improving `setup.py` to automatically handle dependencies.

**Comment by yuyu2172** [comment]
From the next release, `pip install chainercv` will work on an environemnt without Cython or NumPy.

**Comment by knorth55** [comment]
@yuyu2172 

error occurs in `master` branch
```
chainercv.utils.bbox._nms_gpu_post: -> [['chainercv/utils/bbox/_nms_gpu_post.c']]
Traceback (most recent call last):
  File "setup.py", line 91, in <module>
    cmdclass=cmdclass,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 51, in build_extensions
    self.check_cython_extensions(self.extensions)
  File "setup.py", line 48, in check_cython_extensions
    """.format(src))
Exception: Cython-generated file 'chainercv/utils/bbox/_nms_gpu_post.c' not found.
                Cython is required to compile chainercv from a development
                branch. Please install Cython or
                download a release package of chainercv.
```

commands

```
docker run -it ubuntu /bin/bash
# in docker session
apt-get update
apt-get install git
apt-get install python-pip
git clone https://github.com/chainer/chainercv.git
cd chainercv
python setup.py install
```

**Comment by Hakuyume** [comment]
@knorth55 From my understanding,
- If you want to build from source (this repository), Cython is required because '*.c' files are not  included in this repository.
- If you want to install from pip package, Cython is not required because pip package will be shipped with `*.c` files.

@yuyu2172 Is my explanation right?

**Comment by knorth55** [comment]
>If you want to build from source (this repository), Cython is required because '*.c' files are not included in this repository.
If you want to install from pip package, Cython is not required because pip package will be shipped with *.c files.

If so, it doen't matter. 
Have you tried with `testpypi` server?

**Comment by Hakuyume** [comment]
> Have you tried with testpypi server?

I have not tried yet.
@yuyu2172 How about you?

**Comment by yuyu2172** [comment]
I didn't know that such a thing exists.
I haven't tried it yet.

**Comment by yuyu2172** [comment]
@Hakuyume 's explanation is same as mine.

**Comment by knorth55** [comment]
>@Hakuyume 's explanation is same as mine.

OK, I look in `sckit-image` code and it seems it works.

**Comment by yuyu2172** [comment]
From version 0.6, this install script will work.

```
docker pull ubuntu
docker run -it ubuntu /bin/bash
# in docker session
apt-get update
apt-get install python-pip
pip install -U pip
pip install chainercv
```

**Comment by knorth55** [comment]
Good!

**Pull request closed without merging**
