### PR TITLE
fix zero division

### PR DESCRIPTION
**Pull request by Hakuyume**
Original PR: #317

### CODE REVIEW

**Comment by yuyu2172** [comment]
Good PR.
Can you add a unittest for `calc_detection_voc_prec_rec`?

**Comment by Hakuyume** [comment]
> Can you add a unittest for calc_detection_voc_prec_rec?

https://github.com/chainer/chainercv/blob/master/tests/evaluations_tests/test_eval_detection_voc.py#L119-L150

**Comment by yuyu2172** [comment]
I mean, could you add a test case that is relavant to this change?
(There is gt bbox, but all of them are difficult).

**Comment by Hakuyume** [comment]
> I mean, could you add a test case that is relavant to this change?
(There is gt bbox, but all of them are difficult).

I see. OK, I will add it.

**Comment by yuyu2172** [comment]
LGTM

**Pull request merged**
