### PR TITLE
standardize tranpose() and resize() tuple format

### PR DESCRIPTION
**Pull request by knorth55**
related to 389 and 393
merge after 393

## What is changed

- follow `resize` and `transpose` `tuple` style (see https://github.com/chainer/chainercv/pull/389#issuecomment-322169182)

### CODE REVIEW

**Comment by yuyu2172** [comment]
Thanks for your contribution.
Perhaps, we should merge your contribution to #393 because #393 should not pass Travis without your commit (e8f2b45).

@Hakuyume

**Comment by knorth55** [comment]
Sure, you can merge or cherry-pick the commit.

**Comment by Hakuyume** [comment]
@knorth55 OK, I merged your commit to #393. Thank you.

**Comment by yuyu2172** [comment]
Again. Thank you.

**Comment by knorth55** [comment]
My preasure

**Pull request closed without merging**
