### PR TITLE
Add YOLO to README

### PR DESCRIPTION
**Pull request by Hakuyume**

### CODE REVIEW

**Comment by yuyu2172** [comment]
The visualization result looks crowded. For instance, people in the third row are not visible because of labels.
Perhaps, the size of the canvas need to be adjusted for better visualization.

The original code may have not produced the desirable image.

**Comment by Hakuyume** [comment]
> The visualization result looks crowded. For instance, people in the third row are not visible because of labels.
Perhaps, the size of the canvas need to be adjusted for better visualization.
>
> The original code may have not produced the desirable image.

I will try. Perhaps, we should reduce the number of images.

**Comment by Hakuyume** [comment]
@yuyu2172 I updated the figure.

**Comment by yuyu2172** [comment]
LGTM

**Pull request merged**
