### PR TITLE
Add COCOKeypointDataset and vis_keypoint_coco

### PR DESCRIPTION
**Pull request by yuyu2172**
Merge after https://github.com/chainer/chainercv/pull/806

# Demo
```python
from chainercv.datasets import COCOKeypointDataset
from chainercv.visualizations import vis_keypoint_coco
import matplotlib.pyplot as plt
data = COCOKeypointDataset(split='val')
img, point, valid = data[10][:3]
vis_keypoint_coco(img, point, valid, markersize=10)
plt.show()

```

# Memo
Point is represented as `[(K, 3)]` in COCO dataset.
The second axis contains `y, x, v`, where `v` is :
```
0: not labeled; 1: labeled, not inside mask;
2: labeled and inside mask
```

The distinction between `1` and `2` are not made in evaluation code.
From what I understand, the distinction is also not made in Detectron.

### CODE REVIEW

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Comment by mitmul** [comment]
How's the progress on this PR? Is it ready for merge or the API design might be still changed?

**Comment by yuyu2172** [comment]
This PR has been pending because I cannot allocate time to upload test data to GCP so that CI can test the implementation of this PR.

**Comment by yuyu2172** [comment]
@Hakuyume

**Pull request merged**
