### PR TITLE
avoid zero division in bbox2loc

### PR DESCRIPTION
**Pull request by knorth55**

### CODE REVIEW

**Comment by yuyu2172** [comment]
How about `np.minimum(..., 1e14)`?

**Comment by Hakuyume** [comment]
How about `eps` which can get from `numpy.finfo`(https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.finfo.html) instead of magic value `1e-14`?

**Comment by Hakuyume** [comment]
This is just a question. Are there any cases that `height` or `width` becomes `0`? According to `assert_is_bbox`, both `height` and `width` should be a positive number (https://github.com/chainer/chainercv/blob/master/chainercv/utils/testing/assertions/assert_is_bbox.py#L25-L28).

**Comment by knorth55** [comment]
`rpn` output `rois` can be `height =0` and `width = 0` at initial state in training.
and this `rois` can be used `proposal_target_creator`

**Comment by knorth55** [comment]
thank you for review.
I updated

**Comment by Hakuyume** [comment]
> rpn output rois can be height =0 and width = 0 at initial state in training.
and this rois can be used proposal_target_creator

I see. That makes sense.

**Pull request merged**
