### PR TITLE
Fix divide by zero

### PR DESCRIPTION
**Pull request by tkerola**
This PR fixes two divide by zero errors.

### CODE REVIEW

**Comment by yuyu2172** [comment]
Thanks for PR.
Can you remove changes other than `eval_detection_voc.py` and `bbox_iou.py`?

**Comment by tkerola** [comment]
Hi, I removed irrelevant commits.

**Comment by Hakuyume** [comment]
@tkerola I think we should not hide zero division error by using `eps` or `1` as a denominator. For example, if the area of the union of two boxes is zero, one of the boxes is invalid (`invalid` means the area is zero or negative). I think it is better to notify users that there is an invalid box.

**Comment by tkerola** [comment]
@Hakuyume I see. I agree with your point. Then it would be better to display a warning when this happens in `bbox_iou`.

As for the `max(1, n_pos[l])` fix, `n_pos[l]` will be zero if all gt bboxes for a certain class are marked as difficult, which will result in the map score being NaN. Do you think that we can keep the fix in this case?

**Comment by Hakuyume** [comment]
> As for the max(1, n_pos[l]) fix, n_pos[l] will be zero if all gt bboxes for a certain class are marked as difficult, which will result in the map score being NaN. Do you think that we can keep the fix in this case?

As you pointed out, `n_pos[l]` can be zero if all ground truth boxes are marked as difficult and this is a valid situation. How about setting recall of the class to `None`? In this case, we need modify `calc_detection_voc_ap` to accept `None`.
Also, I think the computation of `prec` can be improved. How about setting a element of `prec` to `np.nan` if the corresponding element of `tp + fp` is zero?

**Comment by Hakuyume** [comment]
I made another PR for this issue because my request was too complicated #322.

**Comment by yuyu2172** [comment]
@tkerola 
Hakuyume and I had a discussion privately, and concluded that more change is required on top of this PR.
Since the change involves code outside of the scope you modified, so we thought it was easier to make a new PR #322.
Is it OK to close this?

**Comment by yuyu2172** [comment]
The #322 has been merged.
Thank you for shedding light on this issue.

**Pull request closed without merging**
