### PR TITLE
Add coarse level class names for OnlineProductsDataset

### PR DESCRIPTION
**Pull request by yuyu2172**

### CODE REVIEW

**Comment by Hakuyume** [comment]
Is it possible to provide `fine_label_names` (simply `label_names`)?

**Comment by yuyu2172** [comment]
It has to be generated by a program.
For instance, the first class belonging to `bicycle` super-class would be `bicycle_0000`.

**Comment by Hakuyume** [comment]
@yuyu2172 Could you solve the conflict?

**Comment by yuyu2172** [comment]
OK

**Pull request merged**
