### PR TITLE
Support list in sliceable datasets

### PR DESCRIPTION
**Pull request by Hakuyume**

### CODE REVIEW

**Comment by yuyu2172** [comment]
https://github.com/Hakuyume/chainercv/blob/c82dd4b5ea4460918d7c6164b9e71a55788ad714/chainercv/chainer_experimental/datasets/sliceable/getter_dataset.py#L69

Please fix the doc.

**Comment by Hakuyume** [comment]
I want to users to use `tuple` officially even if `list` is accepted. This PR is only for careless users.

**Comment by Hakuyume** [comment]
I'm using some `list` styles in #457. Perhaps, it is better to rewrite them with `tuple` style.

**Comment by yuyu2172** [comment]
LGTM

**Pull request merged**
