### PR TITLE
pfnCI on Chainer repository

### PR DESCRIPTION
**Pull request by Hakuyume**

### CODE REVIEW

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by yuyu2172** [comment]
I forgot why this PR is necessary

**Comment by Hakuyume** [comment]
This PR allows Chainer's repo (`chainer/chainer`) to use ChainerCV's tests in Chainer's CI.

**Comment by yuyu2172** [comment]
OK. Thanks

**Pull request merged**
