### PR TITLE
Update to v0.7.0

### PR DESCRIPTION
**Pull request by yuyu2172**
I am still writing a release note.

### CODE REVIEW

**Comment by yuyu2172** [comment]
https://gist.github.com/yuyu2172/979f870c3b531195b47cbfd75e5b99e1

Release note.

**Comment by yuyu2172** [comment]
@Hakuyume 
What do you think about releasing today?

**Comment by Hakuyume** [comment]
@yuyu2172 It's OK. Will it be the last release for Chainer v2?

**Comment by yuyu2172** [comment]
Yes.

**Comment by Hakuyume** [comment]
GPU tests passed.

**Pull request merged**
