### PR TITLE
add fcis examples_tests

### PR DESCRIPTION
**Pull request by knorth55**
add fcis example_tests

### CODE REVIEW

**Comment by Hakuyume** [comment]
In #842, I modified pfcCI to check examples_tests. After that PR is merged, I'll check this PR.

**Comment by Hakuyume** [comment]
@knorth55 Can you merge master branch into this PR? I added two environment variables `PFNCI_SKIP` and `SAMPLE` that will help you to write example tests. Please use them.

**Comment by knorth55** [comment]
@Hakuyume I updated to use `SAMPLE` and `PFNCI_SKIP`.

**Comment by knorth55** [comment]
@Hakuyume Now, I really updated.

**Comment by knorth55** [comment]
I merge `origin/master`.

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by knorth55** [comment]
@Hakuyume I updated. can you start test again?

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Pull request merged**
