### PR TITLE
Add Light-Head R-CNN

### PR DESCRIPTION
**Pull request by knorth55**
~merge after #773~
~merge after #795 and #796~

## Light-head RCNN

- [x] add links
- [x] add demo
- [x] add training code
- [x] add test
- [x] update evaluation score
- [x] update pretrained model
- [x] add doc
- [x] add examples_tests

### CODE REVIEW

**Comment by knorth55** [comment]
Current score
```
mmAP (all): 0.39435214
mmAP (large): 0.54053783
mmAP (medium): 0.43851328
mmAP (small): 0.22123997
```

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Comment by yuyu2172** [comment]
Could you add example_tests?
Also, docs?

**Comment by knorth55** [comment]
I update to add docs and examples_tests

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Comment by yuyu2172** [comment]
pfnCI, test this please

**Comment by knorth55** [comment]
I update to pass CI test, probably.

**Pull request merged**
