### PR TITLE
use write_image in tests

### PR DESCRIPTION
**Pull request by Hakuyume**

### CODE REVIEW

**Comment by yuyu2172** [comment]
I am not sure if it is a good idea to introduce an extra dependency.

**Comment by Hakuyume** [comment]
It is better to use well-tested function than to write slicing and transposing directly.

**Comment by yuyu2172** [comment]
OK.
If so, it would be better to change tests for `read_image`.

**Comment by Hakuyume** [comment]
> If so, it would be better to change tests for read_image.

OK, I will fix it.

**Comment by yuyu2172** [comment]
LGTM

**Pull request merged**
