### PR TITLE
add prepare_model_param

### PR DESCRIPTION
**Pull request by knorth55**
use `preset_params` and `prepare_model_param`

- [x] resnet
- [x] vgg
- [x] senet
- [x] faster_rcnn_vgg
- [x] faster_rcnn_fpn
- [x] ssd
- [x] yolo
- [x] segnet
- [x] pspnet
- [x] fcis
- [x] mask_rcnn_fpn
- [x] deeplab

### CODE REVIEW

**Comment by knorth55** [comment]
Now we use `preset_params` in all models

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
@knorth55 Can you separate this PR into the following parts?
- Add `prepare_model_param` and use it in models
- Improve/Refactor examples/tests

**Comment by knorth55** [comment]
move to #869 #871 and #872

**Pull request closed without merging**
