### PR TITLE
Fix ResNets when initialW is specified

### PR DESCRIPTION
**Pull request by yuyu2172**
The program failed when `initialW is not None` because `conv_initialW` is unspecified.

### CODE REVIEW

**Comment by yuyu2172** [comment]
@Hakuyume
Can you check this?
This depends on other PRs.

**Comment by Hakuyume** [comment]
Don't we need `fc_initial_bias`?

> This depends on other PRs.

Which PRs? I wiil check them first.

**Comment by Hakuyume** [comment]
Perhaps, we can use `initialW`, `fc_initialW` and `fc_initial_bias`. Since most of layers in ResNet are `Convolution2D`, users can understand `initialW` means `initialW` for conv.

Another solution is adding `fc_kwargs` that is a `dict` including `initialW` and `initial_bias`.
This is consistent with `bn_kwargs` that we use in many other parts.

**Comment by yuyu2172** [comment]
> Another solution is adding fc_kwargs that is a dict including initialW and initial_bias.
This is consistent with bn_kwargs that we use in many other parts.

Nice.

**Pull request merged**
