### PR TITLE
Update to v0.8.0

### PR DESCRIPTION
**Pull request by yuyu2172**
Release note
https://gist.github.com/yuyu2172/67a50aa86e9a7302768dc968536ee307

### CODE REVIEW

**Comment by yuyu2172** [comment]
@Hakuyume

**Comment by Hakuyume** [comment]
@yuyu2172 Could you update this line? https://github.com/chainer/chainercv/blob/master/setup.py#L25

**Comment by Hakuyume** [comment]
I confirmed that nosetests (w/o `disk`) passed successfully in both Chainer/CuPy 3.2 and Chainer/CuPy 4.0.0b2.

**Comment by yuyu2172** [comment]
Thanks

**Pull request merged**
